# Generated by Django 4.2.9 on 2024-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='post_photos/')),
                ('title', models.CharField(max_length=200)),
                ('characteristics', models.TextField()),
                ('description', models.TextField()),
                ('store_link', models.URLField()),
            ],
        ),
    ]
